/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RootKata;

import java.io.File;
public class DrivingHistoryApp {

    public static void main(String[] args) {
        if (args.length == 0) {
            System.out.println("Please pass <input file path> as an argument ..");
        } else {
            File inputFile  = new File(args[0]);
            parseFile(inputFile);

        }
    }

    static void parseFile(File inputFile) {
        if (inputFile.isFile()) {
            System.out.println("Driving History for input drivers:");
            System.out.println(TripInputParser.parse(inputFile));
        } else {
            System.out.println("The file path you entered is not valid, please enter valid path!");
        }
    }
}
