/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RootKata;

import java.io.File;
import java.util.HashMap;
import java.util.List;

public class DrivingHistoryApp {

    public static void main(String[] args) {
        if (args.length == 0) {
            System.out.println("Please pass <input file path> as an argument ..");
        } else {
            File inputFile  = new File(args[0]);
            HashMap<String, List<Trip>> parsedInput =  TripInputParser.parse(inputFile);
            System.out.println("Driving History for input drivers:");
        }
    }
}
